### ISSUE TITLE
[Bug] Non-responsive on 3840 x 2160 resolution

### ISSUE THREAD

**Issue by sabatale** [Datlyfe/jira_clone#12]
Thanks for this project! It looks like there is a difference in responsiveness between the Vue and React version:

**Vue:**
![image](https://user-images.githubusercontent.com/50220345/95026930-c8c75380-0662-11eb-8eee-dbf3f7a48d2f.png)

**React:**
![image](https://user-images.githubusercontent.com/50220345/95026937-d41a7f00-0662-11eb-912c-653e229a21ea.png)

**Comment by Datlyfe** [comment]
This is not really a bug , it intended to be that way because having the tasks stretch to fit the screen doesn't make sense so they have a max-width
