### ISSUE TITLE
Installation problem: Can I use phpMyAdmin instead of postgreSQL?

### ISSUE THREAD

**Issue by adam1920** [Datlyfe/jira_clone#7]
Can I use phpMyAdmin instead of postgreSQL ?

**Comment by Datlyfe** [comment]
@adam1920, The project is using TypeORM for connecting and interacting with the database.
If you want to use Mysql/MariaDb for your database you can change the config to use Mysql instead of PostgreSQL
[typeorm docs](https://typeorm.io/#/using-ormconfig)
